
CREATE TABLE test
(
    employee_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    username    VARCHAR2(50) NOT NULL,
    phone       VARCHAR2(50),
    email       VARCHAR2(50),
    PRIMARY KEY (employee_id)
);